import turtle

myTurtle = turtle.Turtle(shape='turtle')
myTurtle.width(4)
myTurtle.circle(100)

myTurtle.left(90)
myTurtle.penup()
myTurtle.forward(100)
myTurtle.pendown()
myTurtle.forward(100)
myTurtle.penup()
myTurtle.backward(100)
myTurtle.left(120)
myTurtle.pendown()
myTurtle.forward(100)
myTurtle.penup()
myTurtle.backward(100)
myTurtle.left(120)
myTurtle.pendown()
myTurtle.forward(100)
myTurtle.penup()
myTurtle.backward(100)
myTurtle.left(120)

turtle.exitonclick()